[package]
name = "stream-util"
version = "0.1.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2018"
readme = "README.md"
keywords = ["cancel", "drain", "futures", "stream"]
categories = ["rust-patterns"]
license = "MIT"

[dependencies]
futures = "0.1"
log = "0.4"

[dev-dependencies]
tokio = "0.1"
